### ISSUE TITLE
1.20.1 crash with hephaestus and create

### ISSUE THREAD

**Issue by bananaOHHHOOOOHAHAHAHAAAAHA** [Alpha-s-Stuff/TinkersConstruct#70] opened 2023-10-08 01:32 UTC
### Minecraft Version

1.20.1

### Fabric/Quilt Version

0.14.22

### Fabric/Quilt API Version

0.89.3+1.20.1

### Hephaestus Version

1.20.1-3.6.3.232

### Describe your issue

Game crashes with create and Hephaestus. apparently its because create and hephaestus both use different versions of porting lib, and i heard that it might be fixed in 1.20.2 but can you fix it in 1.20.1 as well? i have a modpack i made and i really dont have the time to port everything to 1.20.2. i would really appreciate it.

### Crash Report

https://mclo.gs/QlhzZQs

### Other mods

create, fabric api and hephaestus

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues

**Comment by AlphaMode** [comment] 2023-10-08 01:36
Duplicate of #64, a fix likely isn't going to be made by create til later versions. There is a fork that you can use that should make the two mods compatible. https://github.com/DM-Earth/create-fabric-dme-edition

**Closed as completed by AlphaMode** 2023-10-08 01:36 UTC
