### ISSUE TITLE
tinkers construct/hephaestus white texture error (again)

### ISSUE THREAD

**Issue by serega10kk** [Alpha-s-Stuff/TinkersConstruct#61] opened 2023-06-26 15:34 UTC
### Minecraft Version

1.18.2 fabric

### Fabric Version

fabric loader 0.14.21

### Hephaestus Version

3.5.2.155

### Describe your issue

white textures on all tools and parts but all liquids looks fine and idk what to do
im playing with my bro on server and he sees all textures fine and all mods the same,playing on a TLauncher
someone says its a sodium error but i dont know how to fix something and dont break the game,sorry

![white error](https://github.com/Alpha-s-Stuff/TinkersConstruct/assets/137806345/5930c1f4-9345-4ad7-b180-47e7275b33b7)
![white texture on wooden sword part](https://github.com/Alpha-s-Stuff/TinkersConstruct/assets/137806345/eadc153f-b04c-4609-9fdc-97dab4776aba)

### Other mods

![all mods](https://github.com/Alpha-s-Stuff/TinkersConstruct/assets/137806345/478b6b26-3396-4eff-b99f-127269768e52)

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues, Searched closed issues

**Comment by serega10kk** [comment] 2023-06-26 15:38
i know it could be a duplicate but i still cant fix it

**Comment by AlphaMode** [comment] 2023-08-10 19:49
Duplicate of #33 usually reloading resources fixes it

**Closed as completed by AlphaMode** 2023-08-10 19:49 UTC
