### ISSUE TITLE
crash when picking up items from part builder

### ISSUE THREAD

**Issue by MNAJakov** [Alpha-s-Stuff/TinkersConstruct#111] opened 2024-03-03 11:48 UTC
### Minecraft Version

1.20.1

### Fabric Version

0.15.7

### Fabric API Version

0.92.0+1.20.1

### Hephaestus Version

1.20.1-3.6.4.270

### Describe your issue

in the latest version with all the mods I have it crashes but on version 1.20.1-3.6.3.241 it works perfectly normal

### Crash Report

(https://mclo.gs/sux0OdT)

### Other mods

[modlist.txt](https://github.com/Alpha-s-Stuff/TinkersConstruct/files/14472783/modlist.txt)

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Sodium

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues

**Comment by MNAJakov** [comment] 2024-03-03 11:53
https://mclo.gs/sux0OdT 
forgot the crash report

**Comment by MNAJakov** [comment] 2024-03-03 11:59
[modlist.txt](https://github.com/Alpha-s-Stuff/TinkersConstruct/files/14472783/modlist.txt)

**Comment by AlphaMode** [comment] 2024-03-03 16:43
Duplicate of #109

**Closed as completed by AlphaMode** 2024-03-03 16:43 UTC
