### ISSUE TITLE
Tools rendered white / Crash on resource reload

### ISSUE THREAD

**Issue by Murk1108** [Alpha-s-Stuff/TinkersConstruct#35] opened 2022-11-27 19:02 UTC
### Minecraft Version

1.18.2

### Fabric/Quilt Version

Quilt 0.17.6

### Fabric/Quilt API Version

qfapi-1.0.0-beta.28_qsl-1.1.0-beta.26_fapi-0.67.0_mc-1.18.2

### Tinkers' Construct Version

1.18.2-3.5.2.155

### Describe your issue

All tool parts are rendered white.

Pressing F3+T to reload sometimes works and the tools are rendered correctly. Sometimes, this does not work and the game crashes with a ConcurrentModificationException.

### Crash Report

https://mclo.gs/LAYp5ca

### Other mods

Only Hephaestus and Quilt Fabric API (all other mods are disabled as seen in the crash report)

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues, Searched closed issues, Checked the FAQ

**Comment by Murk1108** [comment] 2022-12-01 06:29
For anyone else having these crashes with a ConcurrentModificationException either on resource reload or when starting the game. Limiting the number of CPUs visible to Java seemed to be a work around. Just add the following argument to in your launcher configuration:

-XX:ActiveProcessorCount=4

I assume this may impact performance. I guess what is happening here is that Minecraft spawns a number of worker threads depending on the amount of CPUs the machine has and be reducing this, it also reduces the risk for a concurrent access to a certain resource. However, this is all wild guess. Anyway, my friends and I can play with this mod in our modpack now. Feel free to close this issue. Maybe this helps someone.

**Comment by NerdyPuzzle** [comment] 2022-12-01 08:17
Fairly sure minecraft runs on a single core, this shouldn't impact performance.

**Comment by AlphaMode** [comment] 2023-06-03 19:11
Duplicate of #33

**Closed as completed by AlphaMode** 2023-06-03 19:11 UTC
