### ISSUE TITLE
Crash when loading with puzzles lib mod installed

### ISSUE THREAD

**Issue by Dynamixd** [Alpha-s-Stuff/TinkersConstruct#89] opened 2023-11-15 02:13 UTC
### Minecraft Version

1.20.1

### Fabric Version

0.14.24

### Fabric API Version

0.90.7+1.20.1

### Hephaestus Version

3.6.3.241

### Describe your issue

Whenever creating or loading world with the hepheastus mod and the puzzles library mod the game will crash.

### Crash Report

https://mclo.gs/CIryThn

### Other mods

Full modlist here https://hastebin.com/share/zahubegena.sql

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Sodium

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by coldReactive** [comment] 2023-12-09 02:15
Can also reproduce: 

With Hephaestus+: https://mclo.gs/7Znz0eq
Without Hephaestus+: https://mclo.gs/mIEkDWJ

Mod list: https://pastebin.com/q6PsZpBY

**Comment by KonSola5** [comment] 2023-12-09 08:14
HephaestusPlus is my addon for Hephaestus: If there's an issue with it, you should report it in https://github.com/KonSola5/HephaestusPlus/issues instead.

And no, my addon doesn't fix the Hephaestus' Puzzles Lib incompatibility.

**Comment by KonSola5** [comment] 2023-12-09 08:17
But the crash log says that the crash was caused by a **ticking entity** in both cases, and the first method in stack trace is from Star.
Throw in the Neurina mod (catches ticking entities and removes them from the world)

**Comment by coldReactive** [comment] 2023-12-09 10:26
> But the crash log says that the crash was caused by a **ticking entity** in both cases, and the first method in stack trace is from Star. Throw in the Neurina mod (catches ticking entities and removes them from the world)

My install hangs instead once Neurina is installed and using Hephaestus without HephaestusPlus. My comment proved it was crashing without your add-on too, so it's specifically Hephaestus so far that's crashing.

Here's the log after installing Neurina and Minecraft started hanging on world load (not the loading screen, but actually rendering the world, just a blank world, unable to move) instead of crashing: https://mclo.gs/S3TtZUd

So no, Neurina doesn't fix the issue.

**Comment by coldReactive** [comment] 2023-12-27 21:06
Here's the log without Magnum Torch and Puzzles Lib installed: https://mclo.gs/Z1AobJJ

Runs fine even with all those mods. Looks like I'll just have to stick to Kibe's "Big Torch." If I want to keep mobs away. Since Torcherino for Fabric doesn't have something that keeps mobs away, and Reliquary (Which has Interdiction Torches) is forge-only.

**Comment by AlphaMode** [comment] 2024-03-02 01:11
Should be fixed in latest

**Closed as completed by AlphaMode** 2024-03-02 01:11 UTC
