### ISSUE TITLE
crash with multiple mods, doesnt happen when hephaestus is disabled

### ISSUE THREAD

**Issue by ianm1647** [Alpha-s-Stuff/TinkersConstruct#58] opened 2023-06-04 06:24 UTC
### Minecraft Version

1.19.4

### Fabric/Quilt Version

0.14.21

### Fabric/Quilt API Version

0.83.0-1.19.4

### Hephaestus Version

3.6.3.204

### Describe your issue

i have a decent amount of mods loaded at the moment, but whenever i added hephaestus to the list, a crash with reach entity attributes ocurred. im not sure much past that , i just know it doesnt crash with the mod not in the list.

also i didnt get a valid crash report so im just going to put a link to the log instead

it doesnt happen with just the mod loaded by itself, but further testing will be happening

### Crash Report

https://pastebin.com/BYd9Zee5

### Other mods

the current list of mods is on the log, i will keep lowering the amount and update you on what is happening

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Sodium

### Searched for known issues?

Searched open issues

**Comment by AlphaMode** [comment] 2023-06-04 06:26
This is a issue with porting lib and entity reach attributes both do the same thing so I dont really see a fix for this

**Comment by ianm1647** [comment] 2023-06-04 07:17
> This is a issue with porting lib and entity reach attributes both do the same thing so I dont really see a fix for this

so what im hearing right now is that origins is incompatible?

**Comment by AlphaMode** [comment] 2023-06-04 07:20
For now yes, if they depend on entity reach attributes. Until a proper solution can be found

**Comment by Sapfirelynx** [comment] 2023-06-15 22:44
I have a similar issue but it crashes with Sodium involved.

**Comment by AlphaMode** [comment] 2023-08-23 00:39
Duplicate of #63 I'll backport a fix sometime in the future for 1.19.4

**Closed as completed by AlphaMode** 2023-08-23 00:39 UTC
