### ISSUE TITLE
Crash when using with create

### ISSUE THREAD

**Issue by C41nn** [Alpha-s-Stuff/TinkersConstruct#100] opened 2023-12-18 17:38 UTC
### Minecraft Version

1.20.1

### Fabric Version

0.14.25

### Fabric API Version

0.88.1+1.20.1

### Hephaestus Version

all versions for 1.20.1

### Describe your issue

crashing when trying to use with create 

### Crash Report

https://pastebin.com/DSHB3itN

### Other mods

Create 

sodium indium iris 

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Sodium, Other (specify under other mods)

### Searched for known issues?

Searched open issues

**Comment by AlphaMode** [comment] 2023-12-18 17:39
Duplicate of #64

**Closed as completed by AlphaMode** 2023-12-18 17:39 UTC
